version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: >
      bash -lc "
      flask db upgrade &&
      python scripts/seed.py &&
      gunicorn -k eventlet -w 1 -b 0.0.0.0:8000 app:app
      "
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${DB_NAME:-allocar}
      POSTGRES_USER: ${DB_USER:-allocar}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-allocar}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY:-minio_access}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY:-minio_secret}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
volumes:
  pgdata:
  minio:
